services:
  postgres:
    image: postgres:latest
    container_name: "dokploy-postgres"
    environment:
      POSTGRES_DB: dokploy
      POSTGRES_USER: dokploy
      POSTGRES_PASSWORD: amukds4wi9001583845717ad2
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - "dokploy-network"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis_data:/data
    networks:
      - "dokploy-network"

  traefik:
    image: traefik:v2.5
    container_name: "dokploy-traefik"
    volumes:
      - "./.docker/dokploy/traefik.yml:/etc/dokploy/traefik/traefik.yml"
      - "./.docker/dokploy/traefik/dynamic/:/etc/dokploy/traefik/dynamic"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    driver: "bridge"
