version: '3.8'
services:
  jellyfin:
    image: jellyfin/jellyfin
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${HASH}.rule=Host(`${JELLYFIN_HOST}`)"
      - "traefik.http.services.${HASH}.loadbalancer.server.port"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://${JELLYFIN_HOST}
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  dokploy-network:
    external: true
