version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:0.30.1
    ports:
      - '8080'
    volumes:
      - training-data:/usr/share/tessdata #Required for extra OCR languages
      - extra-configs:/configs
      # - /location/of/customFiles:/customFiles/
      # - /location/of/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB

volumes:
  training-data: {}
  extra-configs: {}