name: Build and Publish Docker image

on:
  push:
    branches: ["feat/docker-images-apps"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME: dokploy/website:latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #   - name: Build Docker image
      #     run: docker build --platform linux/amd64 --tag dokploy/website:testing -f Dockerfile .

      #   - name: Push Docker image
      #     run: docker push dokploy/website:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.docs
          push: true
          tags: dokploy/docs:latest
          platforms: linux/amd64
