name: Docker Build

on:
  pull_request:
    branches: [main, canary, feat/github-runners]
env:
  IMAGE_NAME: dokploy/dokploy

jobs:
  docker-amd:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set tag and version
        id: meta
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            TAG="latest"
            VERSION=$(node -p "require('./apps/dokploy/package.json').version")
          elif [ "${{ github.ref }}" = "refs/heads/canary" ]; then
            TAG="canary"
          else
            TAG="feature"
          fi
          echo "tags=${IMAGE_NAME}:${TAG}-amd64" >> $GITHUB_OUTPUT

      - name: Prepare env file
        run: |
          cp apps/dokploy/.env.production.example .env.production
          cp apps/dokploy/.env.production.example apps/dokploy/.env.production

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  docker-arm:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set tag and version
        id: meta
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            TAG="latest"
            VERSION=$(node -p "require('./apps/dokploy/package.json').version")
          elif [ "${{ github.ref }}" = "refs/heads/canary" ]; then
            TAG="canary"
          else
            TAG="feature"
          fi
          echo "tags=${IMAGE_NAME}:${TAG}-arm64" >> $GITHUB_OUTPUT

      - name: Prepare env file
        run: |
          cp apps/dokploy/.env.production.example .env.production
          cp apps/dokploy/.env.production.example apps/dokploy/.env.production

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
